### ISSUE TITLE
Will a ESP32-WROOM-32E work?

### ISSUE THREAD

**Issue by vanAndel** [thaanstad/ESP32_CanOpenNode#1]
Hi Trevor,
Thanks for putting together this ESP32 implementation for CanOpen.  Just a question, will it work on a ESP32-WROOM-32E?  I am hoping to use the board created by https://wesp32.com/ so that I can have POE.  Also, what CAN BUS transceiver will work?  Would the SN65HVD230 work?

Thanks so much,
Shawn

**Comment by thaanstad** [comment]
The code compiles in my Arduino environment for the Adafruit Feather ESP32 variant of the ESP32-Wroom-32E (had to change RX GPIO pin to one that is supported by the Wroom).  I don't have a way to test with this board, but I assume it will work since it is leveraging ESP-SDK.  

My custom PCBA uses the MAX33012EASA+.  The SN65HVD230 doesn't have a STBY output so I would suggest updating the code accordingly.

I have made a few improvements to the library by cleaning up the code a bit.  I'll see if I can get the updates tested and posted this weekend.  Good luck with your project!

**Comment by vanAndel** [comment]
Hi Trevor, thanks for your response.  I'll probably buy both transceivers to see which one I can get working.  Thanks again for putting this together its going to be a great help.
Shawn
